### ISSUE TITLE
extract_desktop unavailable in PIP package

### ISSUE THREAD

**Issue by berarma** [gnome-keysign/babel-glade#2]
Hi. I'm new to Python and I've found this package useful. When installing with pip the extract_desktop function is missing though.

Best regards.

**Comment by muelli** [comment]
hm. that's weird. I have added an `__init__.py`.  That should help discovering it.
https://github.com/gnome-keysign/babel-glade/commit/ac65f63fca671c619d0d7f04948d614c317261fb

does that fix your problem?
